<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AllVerge.Core\AllVerge.Core.csproj" />
    <ProjectReference Include="..\AllVerge.Core.Markup\AllVerge.Core.Markup.csproj" />
    <ProjectReference Include="..\AllVerge.Core.Model.JsonSchema\AllVerge.Core.Model.JsonSchema.csproj" />
    <ProjectReference Include="..\AllVerge.Core.Model.SwaggerTypes\AllVerge.Core.Model.SwaggerTypes.csproj" />
    <ProjectReference Include="..\AllVerge.Core.ServiceModel.Description\AllVerge.Core.ServiceModel.Description.csproj" />
  </ItemGroup>

</Project>
