//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllVerge.MessagingModel.MessagingFoundation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllVerge.MessagingModel.MessagingFoundation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming message for operation &apos;{0}&apos; (contract &apos;{1}&apos; with namespace &apos;{2}&apos;) contains an unrecognized http body format value &apos;{3}&apos;. The expected body format value is &apos;{4}&apos;..
        /// </summary>
        internal static string InvalidHttpMessageFormat {
            get {
                return ResourceManager.GetString("InvalidHttpMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; in contract &apos;{1}&apos; uses &apos;{2}&apos;, but also has body parameter &apos;{3}&apos;. {2} operations cannot have a body. Either make the parameter &apos;{3}&apos; a UriTemplate parameter, or switch to another ResourceActionAttribute that allows a body..
        /// </summary>
        internal static string MethodCannotHaveBody {
            get {
                return ResourceManager.GetString("MethodCannotHaveBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; in contract &apos;{1}&apos; uses &apos;{2}&apos;, but also has a parameter of MessageContract type &apos;{3}&apos;. {2} operations cannot have a body. To use a MessageContract parameter type, switch to a ResourceActionAttribute that allows a body..
        /// </summary>
        internal static string MethodCannotHaveMCParameter {
            get {
                return ResourceManager.GetString("MethodCannotHaveMCParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formatter &apos;{0}&apos; does not support serializing MessageVersion &apos;{1}&apos;..
        /// </summary>
        internal static string SerializingMessageVersionNotSupportedByFormatter {
            get {
                return ResourceManager.GetString("SerializingMessageVersionNotSupportedByFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formatter &apos;{0}&apos; does not support serializing a non-zero number of parameters..
        /// </summary>
        internal static string SerializingParametersNotSupportedByFormatter {
            get {
                return ResourceManager.GetString("SerializingParametersNotSupportedByFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations must specify at least one message..
        /// </summary>
        internal static string ServiceOperationMustSpecifyAtLeastOneMessage {
            get {
                return ResourceManager.GetString("ServiceOperationMustSpecifyAtLeastOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations marked with IsInitiating=true must specify a request message..
        /// </summary>
        internal static string ServiceOperationsMarkedWithIsInitiatingMustNotSpecifyRequestMessage {
            get {
                return ResourceManager.GetString("ServiceOperationsMarkedWithIsInitiatingMustNotSpecifyRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations marked with &apos;{0} must not specify a request message..
        /// </summary>
        internal static string ServiceOperationsMarkedWithResourceActionAttributeMustNotSpecifyRequestMessage {
            get {
                return ResourceManager.GetString("ServiceOperationsMarkedWithResourceActionAttributeMustNotSpecifyRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations marked with &apos;{0} must not specify a response message..
        /// </summary>
        internal static string ServiceOperationsMarkedWithResourceActionAttributeMustNotSpecifyResponseMessage {
            get {
                return ResourceManager.GetString("ServiceOperationsMarkedWithResourceActionAttributeMustNotSpecifyResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected operation message direction; expected &apos;{0}&apos;, found &apos;{1}&apos;..
        /// </summary>
        internal static string ServiceOperationUnexpectedMessage {
            get {
                return ResourceManager.GetString("ServiceOperationUnexpectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CallbackContract {0} is invalid because it is not decorated with a ResourceContractAttribute or CallBackResponseContractAttribute..
        /// </summary>
        internal static string SFxInvalidCallbackContractType {
            get {
                return ResourceManager.GetString("SFxInvalidCallbackContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Version &apos;{0}&apos; is not supported for the operation..
        /// </summary>
        internal static string SFxMessageVersionNotSupportedOperation {
            get {
                return ResourceManager.GetString("SFxMessageVersionNotSupportedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferMessageEncodingMessageProperty: MessageEncoding={0}..
        /// </summary>
        internal static string TransferMessageEncodingMessagePropertyToString {
            get {
                return ResourceManager.GetString("TransferMessageEncodingMessagePropertyToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming transfer message, with content type &apos;{0}&apos;, was mapped to an unknown content format &apos;{1}&apos; by the ContentTypeMapper. Configure the TransferMessageEncodingBindingElement with a ContentTypeMapper that maps the content type to a known TransferMessageEncodings value..
        /// </summary>
        internal static string UnknownTransferEncodingFormat {
            get {
                return ResourceManager.GetString("UnknownTransferEncodingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming message has an unexpected message format &apos;{0}&apos;. The expected message formats for the operation are {1}..
        /// </summary>
        internal static string UnrecognizedHttpMessageFormat {
            get {
                return ResourceManager.GetString("UnrecognizedHttpMessageFormat", resourceCulture);
            }
        }
    }
}
