<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
    <AssemblyName>AllVerge.MessagingModel.Markup.Yaml</AssemblyName>
    <RootNamespace />
    <IsPackable>true</IsPackable>
    <SignAssembly>false</SignAssembly>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Label="MultilingualAppToolkit">
    <MultilingualAppToolkitVersion>4.0</MultilingualAppToolkitVersion>
    <MultilingualFallbackLanguage>en-US</MultilingualFallbackLanguage>
    <TranslationReport Condition="'$(Configuration)' == 'Release'">true</TranslationReport>
    <SuppressPseudoWarning Condition="'$(Configuration)' == 'Debug'">true</SuppressPseudoWarning>
  </PropertyGroup>

  <Import Project="$(MSBuildExtensionsPath)\Microsoft\Multilingual App Toolkit\Microsoft.Multilingual.ResxResources.targets" Label="MultilingualAppToolkit" Condition="Exists('$(MSBuildExtensionsPath)\Microsoft\Multilingual App Toolkit\v$(MultilingualAppToolkitVersion)\Microsoft.Multilingual.ResxResources.targets')" />

  <Target Name="NugetPackAutoVersioning" AfterTargets="Build">
    <Exec Command="dotnet pack --version-suffix &quot;build.$([System.DateTime]::UtcNow.ToString(yyMMddHHmmss))&quot; -p:PackageVersion=$(VersionPrefix)-build.$([System.DateTime]::UtcNow.ToString(yyMMddHHmmss)) --no-build --configuration $(Configuration) --output $(SolutionDir)/nupkgs" />
  </Target>

  <ItemGroup>
    <None Remove="Resources\xlf\*.xlf" />
  </ItemGroup>
  <ItemGroup>
    <XliffResource Include="MultilingualResources\*.xlf" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SystemPrimitives\AllVerge.SystemPrimitives.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="..\AllVerge.MessagingModel.MarkupPrimitives\AllVerge.MessagingModel.MarkupPrimitives.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="..\..\MessagingFoundation\src\System.ServiceModel.Primitives\src\MessagingFoundation.Primitives.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AllVerge.SystemPrimitives" Version="1.0.0-*" />
    <PackageReference Include="AllVerge.MessagingModel.MarkupPrimitives" Version="1.0.0-*" />
    <PackageReference Include="MessagingFoundation.Primitives" Version="6.0.0-*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\AMMMYR.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AMMMYR.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\AMMMYR.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AMMMYR.Designer.cs</LastGenOutput>
      <CustomToolNamespace>System.Runtime.Serialization.Yaml</CustomToolNamespace>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>