<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <Target Name="NugetPackAutoVersioning" AfterTargets="Build">
    <Exec Command="dotnet pack --version-suffix &quot;build.$([System.DateTime]::UtcNow.ToString(yyMMddHHmmss))&quot; -p:PackageVersion=$(VersionPrefix)-build.$([System.DateTime]::UtcNow.ToString(yyMMddHHmmss)) --no-build --configuration $(Configuration) --output $(SolutionDir)/nupkgs" />
  </Target>

  <Target Name="ChangeAliasesOfReferences" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'System.ServiceModel.Primitives'">
        <!-- Give the desired alias to the file here -->
        <Aliases>ServiceModelPrimitives</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>

  <ItemGroup>
    <PackageReference Include="MessagingFoundation.Primitives" Version="6.0.0-*" />
    <PackageReference Include="AllVerge.MessagingModel.RoutingPrimitives" Version="1.0.0-*" />
    <PackageReference Include="AllVerge.MessagingModel.Policy.Client" Version="1.0.0-*" />
  </ItemGroup>

</Project>
